### ISSUE TITLE
Using the Python module vs using AdminLTE by itself

### ISSUE THREAD

**Issue by brunodantas** [fseesink/django-adminlte3-tutorial#1]
Hey, I found this repo on an [issue](https://github.com/d-demirci/django-adminlte3/issues/13#issuecomment-643468662) of the module repo and thought it would be more appropriate to ask this question here.

As a beginner to front-end stuff, I'm curious about what are the advantages of using this Python module instead of just getting the official theme. Like, why depend on the module maintainers when I could try to work directly with AdminLTE?

And besides that, I'm really confused about if it's good practice to use Django templates and its admin site in commercial applications. It seems that the modularity of having a separate front-end has its benefits, but on the other hand it seems that simple CRUD applications would benefit a lot from the Django admin site.

**Comment by fseesink** [comment]
Hey @brunodantas .  Sorry, missed that this came to me.

As for "what are the advantages of using this Python module instead of just getting the official theme", the short answer is time.

IF the module is maintained properly, then you don't really need to do much on your own end other than the initial install of the module and once in awhile doing a `pip install --upgrade django-adminlte`.  If there's been an update to AdminLTE, you get all the updates in one go.

And if you're working in any kind of CI/CD pipeline where you define a requirements.txt file and have your software spin up in a virtualenv, container, etc., you know that on each deployment, your code will have the latest release.  In short, the work of one (the module maintainer) benefits the many.

The module itself includes more than just the AdminLTE files, as the module writer put templates in place to handle the basics.  This can save folks just starting out a lot of time, as they have all the Jinja2 info already in them (header, footer, etc.)  The module also provides a way to use the AdminLTE UI for the built-in Django admin tools.  Whether that's useful to folks depends on who you ask.

But it really comes down to time.  Of course, I wrote "IF" in all caps, as it seems that the dev in question hasn't exactly been maintaining that module of late, which is unfortunate.

I'm afraid I don't understand your last bit, though.  Using AdminLTE, whether directly or via `pip`, doesn't violate the fundamental design/architecture of the Django framework.  It's just a "pretty" layer to make a site look nicer.  It lets you build a nicer UI, if the UI you're looking for is an admin-type panel, with little effort.  It's no different than using any other front-end templating solution, whether straight up Bootstrap, etc.

Also not sure I follow the part about "on the other hand it seems that simple CRUD applications would benefit a lot from the Django admin site."  Using AdminLTE does not in any way affect that.  The one thing you decide is if you want to use the AdminLTE theme in your admin pages.  But again, it's just "the pretty".  Functionality-wise, it's pretty much the same either way.

**Comment by brunodantas** [comment]
Thanks for the answer @fseesink, it makes sense. Indeed my fear about using this kind of module is depending on a third party that may abandon the project, like it seems to have happened. So if it's mainly about saving time, then it seems that using this kind of module would depend on the degree of control one would want over their project.

I meant the last part of my question to be about a different but related subject. It's not about using themes on full-Django sites, it's about making full-Django sites versus using Django only as backend (with an API) plus a completely separated javascript frontend. I've been searching about this and it seems that the latter option is the current trend, and it seems to make sense to separate backend and frontend, especially for complex systems. So with this in mind, I've been trying to understand what are the use cases of Django's UI functionalities nowadays, with those being the admin site and the [Django template system](https://docs.djangoproject.com/en/3.2/topics/templates/) (or Jinja).

The Django template system reminds me a lot of what I've seen on an introductory PHP course, which is putting special tags on HTML pages that are filled during runtime by the server and then sent to the user. My issue is that I'm trying to understand if that's still how things are done in web development, and if so, in what kinds of (commercial) application.
(and the alternative to that seems to be a separate JS frontend that gets resources from a Django rest API via Ajax)

**Comment by fseesink** [comment]
I think the answer here is "it depends".  To my understanding, and keep in mind my use of Django is relatively recent vs. its history, Django was originally developed by folks in, effectively, the newspaper business.  They built a framework to help them build sites to get things done.  Fast forward a good bit, and Django's template system/etc. is seen as one of the more secure ones out there, handling things like field validation both on the frontend using JavaScript before forms are submitted (and JS that devs did not have to write) and on the backend before data gets ingested.  That is a powerful combo for an all-in-one setup.

But you are correct.  The current trend is towards building REST API backends, then building frontends on top of that.  So using Django for the backend and something else for the frontend is definitely an option.  And if you're ok with that, sure, go that route.

However, keep in mind that this requires using multiple languages (so higher friction level), and context switching between programming languages adds complexity/time.  Django was intended for folks who wanted to work solely in Python.  And in that context it works great.

I would disagree with your last bit, though.  While Django has inverted the words used for each, they do follow a kind of MVC (Model View Controller) approach of separating logic from presentation.  I believe the term is MTV (Model Template View).  Likely because of who originally developed it, they did not use the same terms.  Django models are like MVC models.  But Django views are more akin to MVC controllers.  And Django templates are a bit like MVC views.  The idea is that you do your logic in the Django views, and you handle presentation using templates.  (Honestly I wish they would've used the standard MVC terms, as this always gives me a headache having to transcode b/w them.)

PHP, by comparison, was designed early on to mix logic with presentation.  Much like ASP, you wrote HTML pages and slapped some PHP code in here and there to add logic to your pages.  I have used PHP since v4 was released over 20 years ago, and one of the things it has going for it is that it is, by far, the easiest to get started with as a server side web programming language.  I understand both why it is popular and why some folks give it grief.  The ease of using PHP is both a blessing and a curse.  For non-CS types, learning to use PHP, and for that matter setting up a PHP webserver, is generally a simple affair.  PHP has a much lower friction level to getting started than, say, Python, for web development.

The challenge is just that:  PHP tends to lead to folks mixing logic with presentation, as that is kind of its DNA.  Nowadays you have things like Laravel, etc., which try to bring more of the modern approach to things.  But it is just so easy to slap a bit of PHP inside an HTML page and vice versa that it takes more effort not to muddy the waters.

Now at work, we're currently using Django in a bit of hybrid setup.  That is, the backend is written in Python using Django.  And yes, we do use AdminLTE with the templates.  But for many bits, we are creating REST API calls, then on the frontend we call those APIs.  The frontend leverages Django's templates using Jinja2 and AdminLTE for "the pretty", though.  So where there is a little bit of JavaScript we do have to write ourselves (notably around making the REST API calls from the frontend), for the most part we work in Python.  Admittedly, those JS frontend bits were done mostly by someone who's far better versed on that end.

But there are also cases where it hasn't made sense to add that layer of complexity to the design and for some apps within our project we just used Django with its templates as intended.  Sometimes the overhead of additional calls (browser GETs page, server returns page, browser runs JS which makes REST call, REST API returns data, browser renders data) vs. a typical Django app (browser GETs page, server returns page with rendered data that browser shows) just isn't worth it.

How/if you write a program varies.  Whatever you do, be careful not to get stuck in the mindset that "this is the way", as if there was one universal way to do things.  Much like folks looking for the perfect programming language, there is no "One ring to rule them all, one ring to find them, One ring to bring them all, and in the darkness bind them".  Everything from languages to frameworks have a unique DNA.  They were written with some initial design parameters/goals which define their underlying nature.  Over time each may add on other features/elements, but none are best at everything.  Each has strengths, weaknesses, and things they simply cannot do.  So choose accordingly based on the task at hand.

For example, I like Python.  It's great for the work I am currently doing.  But do I think it's a great language for building desktop GUI or mobile apps, for example?  No, not really.  I think Python GUI apps are a bit slow.  Generally speaking, a compiled language would provide a more responsive app (e.g., Swift for macOS/iOS apps, C++ for Windows, etc.).  Would I write a GUI app using Python?  Depends.  If it's something small/simple like a simple GUI for some specific work with limited expected features/maintenance, I might if I knew I could bang it out quicker in Python than I could by having to learn/use another language I haven't spent time on.  But if I know I am going to be developing a larger GUI application from the start, one expected to grow over time with new features/maintenance, odds are I'd use something else.  The startup time might be longer, but in the end the benefits of using the right language would more than pay for itself.

So whether you use Django just for backend work creating a REST API and use something completely separate for the frontend, or whether you use Django alone, there is no one right answer.  It depends.

**Comment by brunodantas** [comment]
Thank you very much for the in-depth response, it makes a lot of sense.
Web development is quite the daunting thing for beginners, isn't it? It seems there's so many options to choose from at every corner and there's never a simple answer for which one to choose.

For now I guess I'll be using Django Rest Framework and see how much I can endure Javascript before I change my mind. And it's nice to see that the Django template system is not "obsolete" either, it seems to be a very practical way to do things, and now I'm convinced that it's not that similar to PHP chaos.
